import type {ChatMessage} from "./type";

export const fakeData: ChatMessage[] = [
	// 2025-02-25
	{
		id: 1,
		type: 'received',
		text: '아니 이게 맞아요?',
		time: '오후 3:31',
		date: '2025 - 02 - 25',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 2,
		type: 'received',
		text: '디자인하기 겁나 힘들다...',
		time: '오후 3:31',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
		replyTo: {
			id: 1,
			text: '아니 이게 맞아요?',
			name: '프로필',
		},
	},
	{
		id: 3,
		type: 'received',
		text: '조아라 딸깍',
		time: '오후 3:31',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 4,
		type: 'sent',
		text: '오늘끝나고 동네한바퀴 긔?',
		time: '오후 5:31',
	},
	{
		id: 5,
		type: 'sent',
		text: '디자인 어케하면 잘할 수 있는것인가.....',
		time: '오후 5:31',
		replyTo: {
			id: 2,
			text: '디자인하기 겁나 힘들다...',
			name: '프로필',
		},
	},
	{
		id: 6,
		type: 'sent',
		text: '답장좀..',
		time: '오후 5:31',
	},
	{
		id: 7,
		type: 'sent',
		text: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
		time: '오후 5:31',
	},
	{
		id: 8,
		type: 'sent',
		text: 'ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ',
		time: '오후 5:32',
	},
	// 2025-02-26
	{
		id: 9,
		type: 'received',
		text: '어제 산책 잘 했어?',
		time: '오전 9:12',
		date: '2025 - 02 - 26',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 10,
		type: 'sent',
		text: '응! 날씨가 좋아서 기분 좋았어.',
		time: '오전 9:13',
		replyTo: {
			id: 9,
			text: '어제 산책 잘 했어?',
			name: '프로필',
		},
	},
	{
		id: 11,
		type: 'received',
		text: '부럽다... 나도 나가고 싶었는데 일이 많았어.',
		time: '오전 9:14',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 12,
		type: 'sent',
		text: '오늘은 시간 괜찮아?',
		time: '오전 9:15',
	},
	{
		id: 13,
		type: 'received',
		text: '오늘은 오후에 미팅이 있어서 힘들 듯 ㅠㅠ',
		time: '오전 9:16',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 14,
		type: 'sent',
		text: '아쉽다! 다음에 같이 나가자~',
		time: '오전 9:17',
	},
	// 2025-02-27
	{
		id: 15,
		type: 'received',
		text: '오늘 점심 뭐 먹을래?',
		time: '오전 11:30',
		date: '2025 - 02 - 27',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 16,
		type: 'sent',
		text: '오늘은 파스타 어때?',
		time: '오전 11:31',
	},
	{
		id: 17,
		type: 'received',
		text: '좋아! 근처에 새로 생긴 곳 있던데 거기 가볼래?',
		time: '오전 11:33',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 19,
		type: 'received',
		text: 'ㅇㅋㅇㅋ~',
		time: '오전 11:33',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 18,
		type: 'sent',
		text: '오 굿! 12시에 로비에서 보자.',
		time: '오전 11:34',
	},
	{
		id: 20,
		type: 'sent',
		text: "",
		img: '/post/post-example.png',
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 21,
		type: 'sent',
		text: "",
		roomTour: {
			master: true,
			name: "그랜마 하우스 302호",
			date: "5월 15일 (목)",
			time: "오후 1:00",
			thumbnail: "/post/post-example.png",
			tourId: 1,
			status: "ing"
		},
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 22,
		type: 'received',
		text: "",
		contract: {
			master: true,
			name: "그랜마 하우스 302호",
			thumbnail: "/post/post-example.png",
			contractId: 1,
			status: "success"
		},
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 23,
		type: 'sent',
		text: "",
		contract: {
			master: false,
			name: "그랜마 하우스 302호",
			thumbnail: "/post/post-example.png",
			contractId: 1,
			status: "fail"
		},
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 24,
		type: 'received',
		text: "",
		img: '/post/post-example.png',
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	},
	{
		id: 25,
		type: 'received',
		text: "",
		roomTour: {
			master: false,
			name: "그랜마 하우스 302호",
			date: "5월 15일 (목)",
			time: "오후 1:00",
			thumbnail: "/post/post-example.png",
			tourId: 1,
			status: "fail"
		},
		time: '오전 11:34',
		profile: '@/assets/meeting/profile.png',
		name: '프로필',
	}
];