import type {Metadata} from "next";
import {GlobalStyles} from '@/components/layout/globalStyle';
import Header from "@/components/ui/header";
import TopLoadingBar from "@/components/layout/loadingbar";
import React from "react";
import {Providers} from "@/components/layout/provider";
import MessageAlert from "@/components/ui/messageAlert";


export const metadata: Metadata = {
	title: "NURI",
	description: "Generated by create next app",
};


export default function RootLayout({children, modal}: { children: React.ReactNode, modal: React.ReactNode }) {
	return (
		<html lang="ko">
		<TopLoadingBar/>
		<MessageAlert/>
		<head>
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		</head>
		<GlobalStyles/>
		<body style={{display: 'flex'}}>
		<Providers>
			<Header/>
			<main className="main-container">
				{children}
				{modal}
			</main>
		</Providers>
		</body>
		</html>
	)
}