import type { Metadata } from "next";
import { GlobalStyles } from '@/components/layout/globalStyle';
import Header from "@/components/ui/header";


export const metadata: Metadata = {
	title: "NURI",
	description: "Generated by create next app",
};


export default function RootLayout({ children, modal }: { children: React.ReactNode, modal: React.ReactNode }) {
	return (
		<html lang="ko">
			<head />
			<GlobalStyles />
			<body style={{ display: 'flex' }}>
				<Header />
				<main
					style={{
						width: '84.5vw',
						height: '100vh',
						maxHeight: '100vh',
						maxWidth: '84.5vw',
					}}
				>
					{children}
					{modal}
				</main>
			</body>
		</html>
	)
}