import type {Metadata} from "next";
import {GlobalStyles} from '@/components/layout/globalStyle';
import Header from "@/components/ui/header";
import TopLoadingBar from "@/components/layout/loadingbar";


export const metadata: Metadata = {
	title: "NURI",
	description: "Generated by create next app",
};


export default function RootLayout({children, modal}: { children: React.ReactNode, modal: React.ReactNode }) {
	return (
		<html lang="ko">
		<TopLoadingBar/>
		<head>
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		</head>
		<GlobalStyles/>
		<body style={{display: 'flex'}}>
		<Header/>
		<main
			style={{
				width: '84.5vw',
				height: '100vh',
				maxHeight: '100vh',
				maxWidth: '84.5vw',
			}}
		>
			{children}
			{modal}
		</main>
		</body>
		</html>
	)
}